export type PlanetPosition = {
  Gate: number;
  Line: number;
  Color?: number;
  Tone?: number;
  Base?: number;
  FixingState?: "None" | "Exalted" | "Detriment";
};

export type PlanetaryPositions = Record<string, PlanetPosition>;

export type HdVariables = {
  Digestion?: "left" | "right";
  Environment?: "left" | "right";
  Awareness?: "left" | "right";
  Perspective?: "left" | "right";
};

export type HumanDesignProfile = {
  user_id: string;
  tipo: string | null;
  estrategia: string | null;
  autoridade: string | null;
  perfil: string | null;
  cruz_incarnacao: string | null;
  // New fields
  assinatura?: string | null;
  tema_nao_self?: string | null;
  definicao?: string | null;
  digestao?: string | null;
  sentido?: string | null;
  sentido_design?: string | null;
  motivacao?: string | null;
  perspectiva?: string | null;
  ambiente?: string | null;
  // Arrays - these are string arrays, not Record
  centros_definidos: string[] | null;
  centros_abertos: string[] | null;
  canais: string[] | null;
  portas: string[] | null;
  // JSONB fields
  variaveis?: HdVariables | null;
  planetas_personalidade?: PlanetaryPositions | null;
  planetas_design?: PlanetaryPositions | null;
  // Dates
  data_nascimento_utc?: string | null;
  data_design_utc?: string | null;
  // Chart visualization (generated by API when valid design param is included)
  chart_url?: string | null; // URL to hosted chart image
  bodygraph_svg?: string | null; // Inline SVG string
  // Raw data
  raw_data: Record<string, unknown> | null;
  created_at?: string;
  updated_at?: string;
};

export type DailyLog = {
  id: string;
  user_id: string;
  data: string;
  hora: string | null; // HH:MM format - allows multiple check-ins per day
  humor_energia: string | null;
  principais_desafios: string | null;
  foco_do_dia: string | null;
  created_at: string;
  updated_at?: string;
};

export type AiMemory = {
  id: string;
  user_id: string;
  source_type: string | null;
  source_id: string | null;
  content: string;
  tags: string[] | null;
  created_at: string;
};

export type AiSession = {
  id: string;
  user_id: string;
  title: string | null;
  created_at: string;
  updated_at: string;
};

// =============================================================================
// HD Friends & Relationships
// =============================================================================

export type HdFriend = {
  id: string;
  user_id: string;
  // Basic info
  name: string;
  relationship_type: string | null;
  notes: string | null;
  // Birth info
  birth_date: string;
  birth_time: string;
  birth_location: string | null;
  timezone: string;
  latitude: string | null;
  longitude: string | null;
  // Human Design data
  tipo: string | null;
  estrategia: string | null;
  autoridade: string | null;
  perfil: string | null;
  cruz_incarnacao: string | null;
  definicao: string | null;
  assinatura: string | null;
  tema_nao_self: string | null;
  // Advanced properties
  digestao: string | null;
  sentido: string | null;
  sentido_design: string | null;
  motivacao: string | null;
  perspectiva: string | null;
  ambiente: string | null;
  // Arrays
  centros_definidos: string[] | null;
  centros_abertos: string[] | null;
  canais: string[] | null;
  portas: string[] | null;
  // JSONB fields
  variaveis: HdVariables | null;
  planetas_personalidade: PlanetaryPositions | null;
  planetas_design: PlanetaryPositions | null;
  // Dates
  data_nascimento_utc: string | null;
  data_design_utc: string | null;
  // Chart visualization
  chart_url: string | null;
  bodygraph_svg: string | null;
  // Raw data
  raw_data: Record<string, unknown> | null;
  // Timestamps
  created_at: string;
  updated_at: string;
};

export type HdRelationship = {
  id: string;
  user_id: string;
  friend_id: string;
  // Relationship Analysis Data
  composite_type: string | null;
  definition_type: string | null;
  // Composite elements
  composite_channels: string[] | null;
  electromagnetic_connections: string[] | null;
  dominance_areas: string[] | null;
  compromise_areas: string[] | null;
  key_themes: string[] | null;
  // Chart
  relationship_svg: string | null;
  // Raw data
  raw_data: Record<string, unknown> | null;
  // Timestamps
  created_at: string;
  updated_at: string;
  // Populated friend data (from joins)
  friend?: HdFriend;
};

// Relationship type options
export const RELATIONSHIP_TYPES = [
  { value: "partner", label: "Parceiro(a)" },
  { value: "family", label: "Família" },
  { value: "friend", label: "Amigo(a)" },
  { value: "colleague", label: "Colega de trabalho" },
  { value: "client", label: "Cliente" },
  { value: "boss", label: "Chefe/Gestor" },
  { value: "employee", label: "Funcionário" },
  { value: "child", label: "Filho(a)" },
  { value: "parent", label: "Pai/Mãe" },
  { value: "sibling", label: "Irmão/Irmã" },
  { value: "other", label: "Outro" },
] as const;

export type RelationshipType = typeof RELATIONSHIP_TYPES[number]["value"];

