-- Add columns to store Bodygraph chart visualization
-- Generated by the Bodygraph API when valid 'design' parameter is included
-- You need to create a design in Bodygraph.com dashboard and set BODYGRAPH_DESIGN_NAME env var

ALTER TABLE public.human_design_profiles
ADD COLUMN IF NOT EXISTS chart_url text,
ADD COLUMN IF NOT EXISTS bodygraph_svg text;

-- Add comments for documentation
COMMENT ON COLUMN public.human_design_profiles.chart_url IS 'URL to the Bodygraph chart image generated by the API.';
COMMENT ON COLUMN public.human_design_profiles.bodygraph_svg IS 'SVG string of the Bodygraph chart. Generated when design param returns inline SVG.';

